library(dplyr) 
data(iris) 
plot(iris$Sepal.Length, iris$Sepal.Width, main="Sepal Length vs Width", col=iris$Species) 
filtered_data <- filter(iris, Species == "setosa") 
print(head(filtered_data, 3)) 
selected_data <- select(iris, Sepal.Length, Sepal.Width) 
print(head(selected_data, 3)) 
mutated_data <- mutate(iris, Sepal.Area = Sepal.Length * Sepal.Width) 
print(head(mutated_data, 3)) 
arranged_data <- arrange(iris, desc(Sepal.Length)) 
print(head(arranged_data, 3))